/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    borderRadius: {
      none: '0px',
      xs: '0px',
      sm: '0px',
      DEFAULT: '0px',
      md: '0px',
      lg: '0px',
      xl: '0px',
      '2xl': '0px',
      '3xl': '0px',
      full: '9999px',
    },
    boxShadow: {
      none: 'none',
      xs: 'none',
      sm: 'none',
      DEFAULT: 'none',
      md: 'none',
      lg: 'none',
      xl: 'none',
      '2xl': 'none',
      inner: 'none',
    },
    extend: {
      colors: {
        thoughtstream: {
          primary: '#78716C',
          secondary: '#A8A29E',
          tertiary: '#1C1917',
          bg: '#FAFAF9',
          surface: '#F5F5F4',
          surfaceRaised: '#EFEDEB',
          textPrimary: '#1C1917',
          textSecondary: '#57534E',
          textTertiary: '#A8A29E',
          borderSubtle: '#E7E5E4',
          borderMedium: '#D6D3D1',
          borderStrong: '#A8A29E',
          success: '#65A30D',
          warning: '#CA8A04',
          error: '#DC2626',
          info: '#78716C',
        },
        diagramaxis: {
          // Estructura (ThoughtStream surface & borders)
          bg: 'rgb(var(--da-bg) / <alpha-value>)',
          surface: 'rgb(var(--da-surface) / <alpha-value>)',
          surface2: 'rgb(var(--da-surface2) / <alpha-value>)',
          surface3: 'rgb(var(--da-surface3) / <alpha-value>)',
          border: 'rgb(var(--da-border) / <alpha-value>)',
          borderLight: 'rgb(var(--da-border-light) / <alpha-value>)',
          brandChip: 'rgb(var(--da-brand-chip) / <alpha-value>)',
          // Acentos ThoughtStream (Stone & Sage)
          gold: 'rgb(var(--da-gold) / <alpha-value>)',
          goldMuted: 'rgb(var(--da-gold-muted) / <alpha-value>)',
          goldHover: 'rgb(var(--da-gold-hover) / <alpha-value>)',
          goldEngraved: 'rgb(var(--da-gold-engraved) / <alpha-value>)',
          orange: 'rgb(var(--da-orange) / <alpha-value>)',
          orangeInk: 'rgb(var(--da-orange-ink) / <alpha-value>)',
          cyan: 'rgb(var(--da-cyan) / <alpha-value>)',
          cyanBright: 'rgb(var(--da-cyan-bright) / <alpha-value>)',
          cyanInk: 'rgb(var(--da-cyan-ink) / <alpha-value>)',
          success: 'rgb(var(--da-success) / <alpha-value>)',
          successHover: 'rgb(var(--da-success-hover) / <alpha-value>)',
          successInk: 'rgb(var(--da-success-ink) / <alpha-value>)',
          warn: 'rgb(var(--da-warn) / <alpha-value>)',
          danger: 'rgb(var(--da-danger) / <alpha-value>)',
          white: 'rgb(var(--da-white) / <alpha-value>)',
          // Materiales neutrales ThoughtStream
          kraft: 'rgb(var(--da-kraft) / <alpha-value>)',
          kraftDark: 'rgb(var(--da-kraft-dark) / <alpha-value>)',
          kraftBorder: 'rgb(var(--da-kraft-border) / <alpha-value>)',
          kraftFg: 'rgb(var(--da-kraft-fg) / <alpha-value>)',
          cork: 'rgb(var(--da-cork) / <alpha-value>)',
          corkLight: 'rgb(var(--da-cork-light) / <alpha-value>)',
          blockWhite: 'rgb(var(--da-block-white) / <alpha-value>)',
          // Texto ThoughtStream
          text: 'rgb(var(--da-text) / <alpha-value>)',
          textBright: 'rgb(var(--da-text-bright) / <alpha-value>)',
          textMuted: 'rgb(var(--da-text-muted) / <alpha-value>)',
          textDim: 'rgb(var(--da-text-dim) / <alpha-value>)',
          // Paneles
          evalBg: 'rgb(var(--da-eval-bg) / <alpha-value>)',
          evalDeep: 'rgb(var(--da-eval-deep) / <alpha-value>)',
          evalBorder: 'rgb(var(--da-eval-border) / <alpha-value>)',
          evalHover: 'rgb(var(--da-eval-hover) / <alpha-value>)',
          overlay: 'rgb(var(--da-overlay) / <alpha-value>)',
          // Fichas
          nodeHead: 'rgb(var(--da-node-head) / <alpha-value>)',
          nodeHeadBorder: 'rgb(var(--da-node-head-border) / <alpha-value>)',
          chipBg: 'rgb(var(--da-chip-bg) / <alpha-value>)',
          chipBorder: 'rgb(var(--da-chip-border) / <alpha-value>)',
          woodMuted: 'rgb(var(--da-wood-muted) / <alpha-value>)',
        },
      },
      fontFamily: {
        serif: ['"Libre Baskerville"', 'Georgia', '"Times New Roman"', 'serif'],
        sans: ['Inter', '-apple-system', '"Segoe UI"', 'Helvetica', 'sans-serif'],
        mono: ['"Source Code Pro"', '"Fira Code"', 'Consolas', 'monospace'],
      },
    },
  },
  plugins: [],
};
